import type { Env } from "../types";
import { listChaseEvents } from "./chaseEvents";
import { trackingStatsForInvoices } from "./chaseTracking";

type InvoiceRow = {
  client_name: string;
  amount: number;
  due_date: string;
  status: string;
  paid_at: string | null;
};

const EVENT_LABELS: Record<string, string> = {
  drafted: "Draft created",
  sent: "Marked sent",
  copied: "Copied to clipboard",
  mailto: "Opened in mail app",
  marked_paid: "Marked paid",
  reply_detected: "Client reply classified",
  note: "Note",
};

export async function generateEvidencePackHtml(
  env: Env,
  accountId: string,
  invoiceId: string
): Promise<{ html: string; clientName: string } | null> {
  const inv = await env.CHASA_DB.prepare(
    `SELECT client_name, amount, due_date, status, paid_at FROM aging_invoices
     WHERE id = ? AND account_id = ?`
  )
    .bind(invoiceId, accountId)
    .first<InvoiceRow>();

  if (!inv) return null;

  const events = await listChaseEvents(env, accountId, { agingInvoiceId: invoiceId, limit: 200 });
  const tracking = await trackingStatsForInvoices(env, accountId, [invoiceId]);
  const stats = tracking[invoiceId];

  const eventRows = events
    .slice()
    .reverse()
    .map(
      (ev) =>
        `<tr><td>${escapeHtml(formatUsDateTime(ev.createdAt))}</td><td>${escapeHtml(EVENT_LABELS[ev.eventType] ?? ev.eventType)}</td><td>${escapeHtml(ev.subject ?? "—")}</td><td>${escapeHtml(ev.bodyPreview?.slice(0, 120) ?? "—")}</td></tr>`
    )
    .join("\n");

  const trackingBlock = stats
    ? `<p><strong>Email tracking (tracked HTML copies):</strong> ${stats.openCount} open(s), ${stats.clickCount} click(s)${stats.lastOpenAt ? ` · last opened ${escapeHtml(formatUsDateTime(stats.lastOpenAt))}` : ""}</p>`
    : `<p><strong>Email tracking:</strong> No tracked sends recorded for this invoice.</p>`;

  const html = `<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<title>Collections evidence — ${escapeHtml(inv.client_name)}</title>
<style>
  body { font-family: Georgia, serif; max-width: 760px; margin: 40px auto; line-height: 1.55; color: #1B3155; font-size: 14px; }
  h1 { font-size: 22px; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
  th, td { border: 1px solid #ccc; padding: 8px; text-align: left; vertical-align: top; }
  th { background: #f5f5f5; }
  .meta { margin: 16px 0; padding: 12px; background: #fafafa; border: 1px solid #ddd; }
  @media print { body { margin: 20px; } }
</style>
</head>
<body>
<h1>Invoice chase evidence record</h1>
<div class="meta">
  <p><strong>Client:</strong> ${escapeHtml(inv.client_name)}</p>
  <p><strong>Amount:</strong> $${inv.amount.toFixed(2)} USD</p>
  <p><strong>Due date:</strong> ${escapeHtml(inv.due_date)}</p>
  <p><strong>Status:</strong> ${escapeHtml(inv.status)}${inv.paid_at ? ` · paid ${escapeHtml(formatUsDateTime(inv.paid_at))}` : ""}</p>
  <p><strong>Generated:</strong> ${escapeHtml(formatUsDateTime(new Date().toISOString()))}</p>
</div>
${trackingBlock}
<h2>Chase timeline</h2>
<table>
  <thead><tr><th>Date</th><th>Action</th><th>Subject</th><th>Preview</th></tr></thead>
  <tbody>
    ${eventRows || `<tr><td colspan="4">No chase events logged yet.</td></tr>`}
  </tbody>
</table>
<p style="margin-top:32px;font-size:12px;color:#666">Generated by docstoc for your records (small claims, collections agency, or internal dispute). Not legal advice.</p>
</body>
</html>`;

  return { html, clientName: inv.client_name };
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatUsDateTime(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}
